plugins {
    id 'com.android.application'
}

android {
    namespace 'com.veilbreakers.prototype'
    compileSdk 35

    defaultConfig {
        applicationId 'com.veilbreakers.prototype'
        minSdk 24
        targetSdk 35
        versionCode 6
        versionName '0.6.0'
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
}