plugins {
    id 'com.android.application'
}

android {
    namespace 'com.veilbreakers.prototype'
    compileSdk 35

    buildFeatures {
        buildConfig true
    }

    defaultConfig {
        applicationId 'com.veilbreakers.prototype'
        minSdk 24
        targetSdk 35
        versionCode 21
        versionName '1.7.0'
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
}
