from pathlib import Path
root=Path('xkiro-ai-studio')

def rep(path,a,b):
 p=root/path; s=p.read_text()
 if a not in s: raise SystemExit(f'missing marker in {path}: {a[:100]}')
 p.write_text(s.replace(a,b,1))

p='app/src/main/java/ai/xkiro/studio/device/DeviceAgentController.kt'
rep(p,'''        val maxRounds = if (command.length > 500) 8 else 6\n        repeat(maxRounds) { round ->''','''        var round = 0\n        while (true) {''')
rep(p,'''            if (cancelled()) return Result("Tarefa interrompida por você.", acted)\n            if (service == null) service = awaitAccessibility(context, 120L)''','''            if (cancelled()) return Result("Tarefa interrompida por você.", acted)\n            round++\n            if (service == null) service = awaitAccessibility(context, 120L)''')
rep(p,'''status(if (frame != null) "Vendo tela nova • rodada ${round + 1}/$maxRounds…" else "Analisando interface • rodada ${round + 1}/$maxRounds…")''','''status(if (frame != null) "Observando tela • etapa $round…" else "Analisando interface • etapa $round…")''')
rep(p,'''OpenRouterOrchestrator.screenVisionPlan(context, settings, visualCommand, snapshot, frame.jpeg, round)''','''OpenRouterOrchestrator.screenVisionPlan(context, settings, visualCommand, snapshot, frame.jpeg, round - 1)''')
rep(p,'''AgentOrchestrator.screenVisionPlan(settings.xkiroKey, visualCommand, snapshot, frame.jpeg, round)''','''AgentOrchestrator.screenVisionPlan(settings.xkiroKey, visualCommand, snapshot, frame.jpeg, round - 1)''')
# second occurrence
f=root/p; s=f.read_text(); s=s.replace('AgentOrchestrator.screenVisionPlan(settings.xkiroKey, visualCommand, snapshot, frame.jpeg, round)','AgentOrchestrator.screenVisionPlan(settings.xkiroKey, visualCommand, snapshot, frame.jpeg, round - 1)'); s=s.replace('planBatch(context, settings, command, snapshot, round)','planBatch(context, settings, command, snapshot, round - 1)'); s=s.replace('''                updateCursor(a)?.let { lastCursor = it }''','''                updateCursor(a)?.let { point ->\n                    lastCursor = point\n                    service?.showAgentCursor(point.first, point.second)\n                }'''); s=s.replace('''        return finish(lastMessage.ifBlank { "Cheguei ao limite de rodadas; mande continuar se ainda faltar algo." }, acted)\n''',''); f.write_text(s)

p='app/src/main/java/ai/xkiro/studio/device/StudioAccessibilityService.kt'
f=root/p; s=f.read_text(); s=s.replace('import android.graphics.Path','''import android.graphics.Path\nimport android.graphics.Color\nimport android.graphics.PixelFormat\nimport android.graphics.drawable.GradientDrawable\nimport android.view.Gravity\nimport android.view.View\nimport android.view.WindowManager\nimport android.os.Handler\nimport android.os.Looper'''); s=s.replace('''    private val generation = AtomicLong(0)\n    val screenVersion: Long get() = generation.get()''','''    private val generation = AtomicLong(0)\n    val screenVersion: Long get() = generation.get()\n    private val mainHandler = Handler(Looper.getMainLooper())\n    private var cursorView: View? = null\n\n    fun showAgentCursor(x: Int, y: Int) {\n        mainHandler.post {\n            val wm = getSystemService(WINDOW_SERVICE) as WindowManager\n            cursorView?.let { runCatching { wm.removeView(it) } }\n            val size = (26 * resources.displayMetrics.density).toInt()\n            val ring = (3 * resources.displayMetrics.density).toInt()\n            val v = View(this).apply {\n                background = GradientDrawable().apply {\n                    shape = GradientDrawable.OVAL\n                    setColor(Color.argb(70, 255, 255, 255))\n                    setStroke(ring, Color.rgb(255, 70, 70))\n                }\n            }\n            val lp = WindowManager.LayoutParams(size, size, WindowManager.LayoutParams.TYPE_ACCESSIBILITY_OVERLAY,\n                WindowManager.LayoutParams.FLAG_NOT_FOCUSABLE or WindowManager.LayoutParams.FLAG_NOT_TOUCHABLE or WindowManager.LayoutParams.FLAG_LAYOUT_NO_LIMITS,\n                PixelFormat.TRANSLUCENT).apply {\n                gravity = Gravity.TOP or Gravity.START\n                this.x = x - size / 2; this.y = y - size / 2\n            }\n            runCatching { wm.addView(v, lp); cursorView = v }\n            mainHandler.postDelayed({ if (cursorView === v) { runCatching { wm.removeView(v) }; cursorView = null } }, 1200)\n        }\n    }'''); s=s.replace('''    override fun onDestroy() { if (instance === this) instance = null; super.onDestroy() }''','''    override fun onDestroy() {\n        cursorView?.let { v -> runCatching { (getSystemService(WINDOW_SERVICE) as WindowManager).removeView(v) } }\n        cursorView = null\n        if (instance === this) instance = null\n        super.onDestroy()\n    }'''); f.write_text(s)

p='app/build.gradle.kts'
rep(p,'versionCode = 15','versionCode = 16')
rep(p,'versionName = "0.2.4"','versionName = "0.2.5"')
