from pathlib import Path
r=Path('xkiro-ai-studio')
def rw(p,a,b):
 f=r/p;s=f.read_text()
 if a not in s: raise SystemExit('missing '+a[:60])
 f.write_text(s.replace(a,b,1))
p='app/src/main/java/ai/xkiro/studio/device/DeviceAgentController.kt'
rw(p,'object DeviceAgentController {\n    @Volatile private var cancelRequested = false\n','object DeviceAgentController {\n    const val VISION_REAUTH_PREFIX = "[[XKIRO_SCREEN_VISION_REAUTH]]"\n    @Volatile private var cancelRequested = false\n')
rw(p,'    data class Result(val message: String, val actedOnDevice: Boolean)\n','    data class Result(val message: String, val actedOnDevice: Boolean, val requiresScreenVisionReauth: Boolean = false)\n')
rw(p,'        if (!ScreenCaptureService.active)\n            return Result("Screen Vision não está autorizado. Toque em \'Compartilhar tela inteira\' e confirme a captura.", false)\n','        if (!ScreenCaptureService.active)\n            return Result("${VISION_REAUTH_PREFIX} Screen Vision precisa ser autorizado novamente.", false, true)\n')
rw(p,'        if (firstFrame == null)\n            return Result("Screen Vision foi autorizado, mas não está entregando vídeo. ${ScreenCaptureService.healthText()}. Reabra \'Compartilhar tela inteira\' e autorize novamente.", false)\n','        if (firstFrame == null)\n            return Result("${VISION_REAUTH_PREFIX} Screen Vision não está entregando quadros recentes. ${ScreenCaptureService.healthText()}", false, true)\n')
rw(p,'''        var acted = false\n        var lastMessage = ""\n        var lastCursor: Pair<Int, Int>? = null\n        var lastObservedFrameAt = 0L\n''','''        var acted = false\n        var lastMessage = ""\n        var lastCursor: Pair<Int, Int>? = null\n        var lastObservedFrameAt = firstFrame.capturedAt\n        var lastActionSignature = ""\n        var repeatedActionCount = 0\n        var stableRounds = 0\n        var lastVisualSignature = 0\n        var emptyPlanCount = 0\n        var recoveryHint = ""\n        if (service?.foregroundPackage() == context.packageName) {\n            status("Saindo do xKiro para controlar o celular visualmente…")\n            service.home(); delay(250L)\n            awaitFreshFrame(firstFrame.capturedAt, 2_000L)?.let { lastObservedFrameAt = it.capturedAt }\n        }\n''')
rw(p,'        suspend fun finish(message: String, didAct: Boolean): Result {\n            if (didAct && message.isNotBlank()','        suspend fun finish(message: String, didAct: Boolean): Result {\n            service?.hideAgentCursor()\n            if (didAct && message.isNotBlank()')
rw(p,'            if (cancelled()) return Result("Tarefa interrompida por você.", acted)\n','            if (cancelled()) { service?.hideAgentCursor(); return Result("Tarefa interrompida por você.", acted) }\n')
rw(p,'''            if (frame == null) {\n                return finish("Screen Vision perdeu o fluxo de vídeo durante a tarefa. ${ScreenCaptureService.healthText()}. Reautorize o compartilhamento da tela inteira.", acted)\n            }\n            lastObservedFrameAt = frame.capturedAt\n''','''            if (frame == null) {\n                service?.hideAgentCursor()\n                return Result("${VISION_REAUTH_PREFIX} Screen Vision perdeu o fluxo durante a tarefa. ${ScreenCaptureService.healthText()}", acted, true)\n            }\n            lastObservedFrameAt = frame.capturedAt\n            val visualSignature = 31 * frame.jpeg.contentHashCode() + snapshot.hashCode()\n            stableRounds = if (visualSignature == lastVisualSignature) stableRounds + 1 else 0\n            lastVisualSignature = visualSignature\n''')
rw(p,'''            val outcomeContext = lastMessage.takeIf { it.isNotBlank() }?.let { "\\nULTIMO_RESULTADO: ${it.take(280)}" }.orEmpty()\n            val visualCommand = command + cursorContext + outcomeContext + """\nMODO COMPUTER USE ESTRITO: controle a tela como uma pessoa. Você NÃO possui open_url/open_app/click_text/click_id/set_text nem atalhos semânticos. Só pode usar tap, double_tap, long_press, swipe, drag, type_text, paste, enter, press_key, back, home, recents, wait, finish e need_confirmation. Para abrir site/app, navegue visualmente e digite/toque na interface. Escolha UMA ação física por frame e observe o frame seguinte antes de continuar.\n"""\n''','''            val outcomeContext = lastMessage.takeIf { it.isNotBlank() }?.let { "\\nULTIMO_RESULTADO: ${it.take(280)}" }.orEmpty()\n            val foreground = service?.foregroundPackage().orEmpty()\n            val stabilityContext = if (stableRounds >= 2 || recoveryHint.isNotBlank()) "\\nESTAGNAÇÃO: tela igual por $stableRounds ciclos. ${recoveryHint.take(240)} Não repita a mesma ação." else ""\n            val visualCommand = command + cursorContext + outcomeContext + stabilityContext + """\nFOREGROUND_PACKAGE=$foreground\nSCREENSHOT=${frame.width}x${frame.height}; DEVICE=${context.resources.displayMetrics.widthPixels}x${context.resources.displayMetrics.heightPixels}. Dê coordenadas no sistema da screenshot; o executor converte para a tela física.\nMODO COMPUTER USE ESTRITO: controle como uma pessoa. Sem open_url/open_app/click_text/click_id/set_text. Só tap, double_tap, long_press, swipe, swipe_direction, drag, type_text, paste, enter, press_key, back, home, recents, wait, finish e need_confirmation. Se xKiro estiver visível, use home e nunca toque nos controles do xKiro. Exatamente UMA ação por frame. Nunca afirme que abriu/carregou algo sem prova visual. finish só quando o frame atual provar conclusão.\n"""\n''')
rw(p,'''            lastMessage = plan.optString("message")\n            val actions = plan.optJSONArray("actions") ?: JSONArray()\n            if (actions.length() == 0) return finish(lastMessage.ifBlank { "Comando concluído." }, acted)\n''','''            lastMessage = plan.optString("message")\n            val actions = plan.optJSONArray("actions") ?: JSONArray()\n            if (actions.length() == 0) {\n                emptyPlanCount++; recoveryHint = "Planejador retornou mensagem sem ação; isso não é progresso."\n                status("Plano vazio • reobservando…")\n                if (emptyPlanCount >= 3) return finish("O planejador visual não propôs ação verificável após 3 tentativas. Parei para não gastar API em loop.", acted)\n                delay(180L); continue\n            } else emptyPlanCount = 0\n''')
