from pathlib import Path
r=Path('xkiro-ai-studio')
def rw(p,a,b):
 f=r/p;s=f.read_text()
 if a not in s: raise SystemExit('missing '+a[:70])
 f.write_text(s.replace(a,b,1))
p='app/src/main/java/ai/xkiro/studio/MainActivity.kt'
rw(p,'    private var utilityTask: Job? = null\n    private var testVoicePlayer: MediaPlayer? = null\n','    private var utilityTask: Job? = null\n    private var screenHealthTask: Job? = null\n    private var testVoicePlayer: MediaPlayer? = null\n    private var pendingDeviceCommand: String? = null\n')
f=r/p;s=f.read_text();a=s.index('    private val capturePermission = registerForActivityResult');b=s.index('\n    private val pickImage =',a)
repl='''    private val capturePermission = registerForActivityResult(ActivityResultContracts.StartActivityForResult()) { result ->\n        if (result.resultCode == Activity.RESULT_OK && result.data != null) {\n            val permissionData=result.data!!; val resultCode=result.resultCode\n            runtimeStatus.text="Reiniciando Screen Vision…"\n            scope.launch {\n                stopService(Intent(this@MainActivity,ScreenCaptureService::class.java))\n                val deadline=System.currentTimeMillis()+1500L\n                while(ScreenCaptureService.active && System.currentTimeMillis()<deadline) delay(80)\n                delay(120)\n                val i=Intent(this@MainActivity,ScreenCaptureService::class.java).putExtra(ScreenCaptureService.EXTRA_RESULT_CODE,resultCode).putExtra(ScreenCaptureService.EXTRA_DATA,permissionData)\n                ContextCompat.startForegroundService(this@MainActivity,i)\n                runtimeStatus.text="Screen Vision: aguardando primeiro quadro…"\n                val until=System.currentTimeMillis()+5000L\n                while(!ScreenCaptureService.isStreaming() && System.currentTimeMillis()<until){ delay(250); runtimeStatus.text="Screen Vision: ${ScreenCaptureService.healthText()}"; updateScreenVisionButton() }\n                if(ScreenCaptureService.isStreaming()){\n                    runtimeStatus.text="Screen Vision: ${ScreenCaptureService.healthText()}"; updateScreenVisionButton()\n                    val pending=pendingDeviceCommand; pendingDeviceCommand=null\n                    if(!pending.isNullOrBlank()){ delay(220); runDevicePrompt(pending,currentSettings()) }\n                } else { runtimeStatus.text="Screen Vision sem vídeo • ${ScreenCaptureService.healthText()}"; out.text="A autorização foi aceita, mas não chegaram quadros da tela. Toque em compartilhar tela novamente." }\n            }\n            toast("Permissão recebida. Validando vídeo real do Screen Vision.")\n        } else { pendingDeviceCommand=null; runtimeStatus.text="Compartilhamento de tela não autorizado"; updateScreenVisionButton() }\n    }\n'''
f.write_text(s[:a]+repl+s[b:])
rw(p,'        scope.launch { delay(550); autoDoctor(false) }\n    }\n','        scope.launch { delay(550); autoDoctor(false) }\n        screenHealthTask=scope.launch { while(isActive){ updateScreenVisionButton(); delay(1000) } }\n    }\n')
rw(p,'''            DeviceAgentController.looksLikeDeviceCommand(text) -> beginTask("Device Agent • visão + ações") {\n                DeviceAgentController.execute(this@MainActivity, s, text) { status ->\n                    runOnUiThread {\n                        out.text = status\n                        runtimeStatus.text = status.substringBefore('…').take(70)\n                    }\n                }.message\n            }\n''','''            DeviceAgentController.looksLikeDeviceCommand(text) -> runDevicePrompt(text,s)\n''')
f=r/p;s=f.read_text();marker='    private fun looksLikeResearchRequest(text: String): Boolean {\n'
if marker not in s: raise SystemExit('research marker missing')
helper='''    private fun runDevicePrompt(text:String,s:StudioSettings=currentSettings()){\n        if(!ScreenCaptureService.isStreaming()){ pendingDeviceCommand=text; out.text="Vou usar o Screen Vision. Autorize o compartilhamento da tela e eu continuo automaticamente."; runtimeStatus.text="Screen Vision precisa de autorização"; startFullScreenVision(); return }\n        activeTask?.cancel(); DeviceAgentController.resetCancellation(); runtimeStatus.text="Device Agent • visão + ações"; findViewById<Button>(R.id.stopScreen).isEnabled=false\n        activeTask=scope.launch {\n            runCatching { DeviceAgentController.execute(this@MainActivity,s,text){ st-> runOnUiThread { out.text=st; runtimeStatus.text=st.substringBefore('…').take(70) } } }\n                .onSuccess { result->\n                    findViewById<Button>(R.id.stopScreen).isEnabled=true\n                    if(result.requiresScreenVisionReauth || result.message.startsWith(DeviceAgentController.VISION_REAUTH_PREFIX)){ pendingDeviceCommand=text; out.text=result.message.removePrefix(DeviceAgentController.VISION_REAUTH_PREFIX).trim()+"\\n\\nVou pedir autorização novamente e continuar."; runtimeStatus.text="Screen Vision caiu • reautorizando"; delay(180); startFullScreenVision() }\n                    else { out.text=result.message; runtimeStatus.text="Pronto"; animateOutput(); scope.launch { runCatching { autoDoctor(false) } } }\n                }.onFailure { err->\n                    findViewById<Button>(R.id.stopScreen).isEnabled=true\n                    if(err is CancellationException){ out.text="Tarefa interrompida por você."; runtimeStatus.text="Interrompido" }\n                    else { out.text="Device Agent falhou: ${err.message}"; runtimeStatus.text="Falha no Device Agent"; scope.launch { runCatching { autoDoctor(false) } } }\n                }\n        }\n    }\n\n    private fun updateScreenVisionButton(){\n        if(!::runtimeStatus.isInitialized) return\n        findViewById<Button>(R.id.shareScreen).text=when{\n            ScreenCaptureService.isStreaming()->"Screen Vision ativo • quadro #${ScreenCaptureService.frameCount}"\n            ScreenCaptureService.active->"Screen Vision autorizado • aguardando vídeo"\n            else->"Compartilhar tela inteira com os agentes"\n        }\n    }\n\n'''
f.write_text(s.replace(marker,helper+marker,1))
rw(p,'    private fun stopScreenSharing() {\n        stopService(Intent(this, ScreenCaptureService::class.java))\n','    private fun stopScreenSharing() {\n        pendingDeviceCommand = null\n        stopService(Intent(this, ScreenCaptureService::class.java))\n')
rw(p,'        utilityTask?.cancel()\n        testVoicePlayer?.release()\n','        utilityTask?.cancel()\n        screenHealthTask?.cancel()\n        testVoicePlayer?.release()\n')
p='app/build.gradle.kts'
rw(p,'versionCode = 19','versionCode = 20');rw(p,'versionName = "0.2.8"','versionName = "0.2.9"')
