from pathlib import Path
r=Path('xkiro-ai-studio')
def rw(p,a,b):
 f=r/p;s=f.read_text()
 if a not in s: raise SystemExit('missing '+a[:80])
 f.write_text(s.replace(a,b,1))
p='app/src/main/java/ai/xkiro/studio/device/DeviceAgentController.kt'
rw(p,'''                val a = actions.optJSONObject(i) ?: continue\n                val type = a.optString("action", "finish")\n                val physical = setOf("tap","double_tap","long_press","swipe","swipe_direction","drag","type_text","paste","enter","press_key","back","home","recents","wait","finish","need_confirmation")\n''','''                val rawAction = actions.optJSONObject(i) ?: continue\n                val a = scaleVisualCoordinates(rawAction, frame, context)\n                val type = a.optString("action", "finish")\n                val physical = setOf("tap","double_tap","long_press","swipe","swipe_direction","drag","type_text","paste","enter","press_key","back","home","recents","wait","finish","need_confirmation")\n''')
rw(p,'''                if (type == "finish") return finish(a.optString("message").ifBlank { lastMessage.ifBlank { "Concluído." } }, acted)\n                if (type == "need_confirmation") return Result(a.optString("message").ifBlank { "Essa próxima ação precisa da sua confirmação." }, acted)\n                status("Device Agent: ${humanAction(type)}…")\n''','''                if (type == "finish") return finish(a.optString("message").ifBlank { lastMessage.ifBlank { "Concluído." } }, acted)\n                if (type == "need_confirmation") { service?.hideAgentCursor(); return Result(a.optString("message").ifBlank { "Essa próxima ação precisa da sua confirmação." }, acted) }\n                val sig = actionSignature(a)\n                if (sig == lastActionSignature) repeatedActionCount++ else repeatedActionCount = 0\n                lastActionSignature = sig\n                if (repeatedActionCount >= 2 && stableRounds >= 1) {\n                    recoveryHint = "A ação $sig repetiu sem avanço visível."\n                    status("Travamento detectado • mudando estratégia…")\n                    if (repeatedActionCount >= 4) return finish("Detectei repetição sem progresso e parei para proteger seus créditos. Última ação: $sig", acted)\n                    delay(160L); break\n                }\n                status("Device Agent: ${humanAction(type)}…")\n''')
rw(p,'''                if (changesScreen) {\n                    if (service != null && before >= 0) service?.waitForScreenChange(before, 500)\n                    if (ScreenCaptureService.active) {\n                        awaitFreshFrame(beforeFrameAt, 1_450L)?.let { lastObservedFrameAt = it.capturedAt }\n                    } else delay(150)\n''','''                if (changesScreen) {\n                    val accessibilityChanged = if (service != null && before >= 0) service.waitForScreenChange(before, 650) else false\n                    val fresh = if (ScreenCaptureService.active) awaitFreshFrame(beforeFrameAt, 1_650L) else null\n                    if (fresh != null) lastObservedFrameAt = fresh.capturedAt else delay(150)\n                    if (accessibilityChanged || (fresh != null && fresh.jpeg.contentHashCode() != frame.jpeg.contentHashCode())) { repeatedActionCount=0; recoveryHint="" }\n''')
rw(p,'''    private suspend fun executeAction(context: Context, service: StudioAccessibilityService?, a: JSONObject): Boolean {\n        return when (a.optString("action")) {\n''','''    private suspend fun executeAction(context: Context, service: StudioAccessibilityService?, a: JSONObject): Boolean {\n        val action = a.optString("action")\n        val selfSensitive = action in setOf("tap","double_tap","long_press","swipe","swipe_direction","drag","type_text","paste","enter","press_key")\n        if (selfSensitive && service?.foregroundPackage() == context.packageName) return false\n        return when (action) {\n''')
marker='    private fun updateCursor(a: JSONObject): Pair<Int, Int>? = when (a.optString("action")) {\n'
f=r/p;s=f.read_text()
if marker not in s: raise SystemExit('helper marker missing')
helper='''    private fun scaleVisualCoordinates(source: JSONObject, frame: ScreenCaptureService.ScreenFrame, context: Context): JSONObject {\n        val a=JSONObject(source.toString())\n        val dw=context.resources.displayMetrics.widthPixels.toDouble().coerceAtLeast(1.0); val dh=context.resources.displayMetrics.heightPixels.toDouble().coerceAtLeast(1.0)\n        val fw=frame.width.toDouble().coerceAtLeast(1.0); val fh=frame.height.toDouble().coerceAtLeast(1.0)\n        fun sx(n:String){ if(a.has(n)) a.put(n,(a.optDouble(n)*dw/fw).coerceIn(0.0,dw-1.0)) }\n        fun sy(n:String){ if(a.has(n)) a.put(n,(a.optDouble(n)*dh/fh).coerceIn(0.0,dh-1.0)) }\n        when(a.optString("action")){\n            "tap","double_tap","long_press"->{sx("x");sy("y")}\n            "swipe","drag"->{sx("x1");sy("y1");sx("x2");sy("y2")}\n        }; return a\n    }\n\n    private fun actionSignature(a:JSONObject):String=when(val t=a.optString("action")){\n        "tap","double_tap","long_press"->"$t:${a.optDouble("x").toInt()/24}:${a.optDouble("y").toInt()/24}"\n        "swipe","drag"->"$t:${a.optDouble("x1").toInt()/32}:${a.optDouble("y1").toInt()/32}:${a.optDouble("x2").toInt()/32}:${a.optDouble("y2").toInt()/32}"\n        "type_text"->"$t:${a.optString("text").hashCode()}"\n        "press_key"->"$t:${a.optString("key")}"\n        else->t\n    }\n\n'''
f.write_text(s.replace(marker,helper+marker,1))
