from pathlib import Path
root=Path('xkiro-ai-studio')
res=root/'app/src/main/res'
layout=res/'layout/activity_main.xml'
s=layout.read_text()
s=s.replace('@drawable/diana_mark','@drawable/diana_mark_exact')
s=s.replace('android:id="@+id/executionBar" android:layout_width="match_parent" android:layout_height="62dp"','android:id="@+id/executionBar" android:layout_width="match_parent" android:layout_height="52dp"',1)
s=s.replace('android:id="@+id/viewExecution" style="@style/Widget.Material3.Button.OutlinedButton" android:layout_width="98dp" android:layout_height="38dp"','android:id="@+id/viewExecution" style="@style/Widget.Material3.Button.OutlinedButton" android:layout_width="98dp" android:layout_height="34dp"',1)
s=s.replace('app:cornerRadius="19dp" app:icon="@drawable/ic_chevron_right"','app:cornerRadius="17dp" app:icon="@drawable/ic_chevron_right"',1)
for idn in ('modeChat','modeWork','modeDevice'):
    s=s.replace(f'android:id="@+id/{idn}" style="@style/Widget.Material3.Button.OutlinedButton" android:layout_width="0dp" android:layout_height="46dp"',f'android:id="@+id/{idn}" style="@style/Widget.Material3.Button.OutlinedButton" android:layout_width="0dp" android:layout_height="40dp"',1)
s=s.replace('app:cornerRadius="23dp" app:icon="@drawable/ic_chat"','app:cornerRadius="20dp" app:icon="@drawable/ic_chat"',1)
s=s.replace('app:cornerRadius="23dp" app:icon="@drawable/ic_work"','app:cornerRadius="20dp" app:icon="@drawable/ic_work"',1)
s=s.replace('app:cornerRadius="23dp" app:icon="@drawable/ic_phone"','app:cornerRadius="20dp" app:icon="@drawable/ic_phone"',1)
s=s.replace('android:background="@drawable/diana_composer" android:orientation="vertical" android:paddingLeft="12dp" android:paddingTop="9dp" android:paddingRight="10dp" android:paddingBottom="8dp"','android:background="@drawable/diana_composer" android:orientation="vertical" android:paddingLeft="12dp" android:paddingTop="7dp" android:paddingRight="10dp" android:paddingBottom="5dp"',1)
s=s.replace('android:id="@+id/prompt" android:layout_width="match_parent" android:layout_height="52dp"','android:id="@+id/prompt" android:layout_width="match_parent" android:layout_height="34dp"',1)
s=s.replace('<LinearLayout android:layout_width="match_parent" android:layout_height="48dp" android:gravity="center_vertical" android:orientation="horizontal">','<LinearLayout android:layout_width="match_parent" android:layout_height="42dp" android:gravity="center_vertical" android:orientation="horizontal">',1)
s=s.replace('android:id="@+id/sendPrompt" android:layout_width="48dp" android:layout_height="48dp"','android:id="@+id/sendPrompt" android:layout_width="42dp" android:layout_height="42dp"',1)
s=s.replace('app:cornerRadius="24dp" app:icon="@drawable/ic_send"','app:cornerRadius="21dp" app:icon="@drawable/ic_send"',1)
start=s.index('        <LinearLayout android:id="@+id/devicePanel"')
end=s.index('        <TextView android:layout_width="match_parent" android:layout_height="wrap_content" android:layout_marginTop="13dp" android:gravity="center" android:letterSpacing="0.32" android:text="FOCO  •  AÇÃO  •  RESULTADOS"',start)
device='''        <LinearLayout android:id="@+id/devicePanel" android:layout_width="match_parent" android:layout_height="wrap_content" android:layout_marginTop="10dp" android:background="@drawable/diana_panel" android:orientation="vertical" android:padding="10dp">
            <LinearLayout android:layout_width="match_parent" android:layout_height="34dp" android:gravity="center_vertical" android:orientation="horizontal">
                <ImageView android:layout_width="21dp" android:layout_height="21dp" android:src="@drawable/ic_phone" app:tint="@color/textSecondary" />
                <TextView android:layout_width="0dp" android:layout_height="wrap_content" android:layout_marginLeft="9dp" android:layout_weight="1" android:text="Controle do aparelho" android:textColor="@color/text" android:textSize="12.5sp" android:textStyle="bold" />
                <TextView android:id="@+id/deviceCount" android:layout_width="wrap_content" android:layout_height="wrap_content" android:text="3/3 ativos" android:textColor="@color/muted" android:textSize="9.5sp" />
                <ImageView android:layout_width="17dp" android:layout_height="17dp" android:layout_marginLeft="4dp" android:src="@drawable/ic_chevron_down" app:tint="@color/muted" />
            </LinearLayout>
            <LinearLayout android:layout_width="match_parent" android:layout_height="wrap_content" android:layout_marginTop="3dp" android:background="@drawable/diana_device_group" android:orientation="vertical" android:paddingLeft="9dp" android:paddingRight="3dp">
                <LinearLayout android:layout_width="match_parent" android:layout_height="46dp" android:gravity="center_vertical" android:orientation="horizontal">
                    <FrameLayout android:layout_width="32dp" android:layout_height="32dp" android:background="@drawable/diana_icon_circle"><ImageView android:layout_width="18dp" android:layout_height="18dp" android:layout_gravity="center" android:src="@drawable/ic_accessibility" app:tint="@color/textSecondary" /></FrameLayout>
                    <LinearLayout android:layout_width="0dp" android:layout_height="wrap_content" android:layout_marginLeft="9dp" android:layout_weight="1" android:orientation="vertical"><TextView android:layout_width="wrap_content" android:layout_height="wrap_content" android:text="Acessibilidade" android:textColor="@color/text" android:textSize="11.5sp" /><TextView android:layout_width="wrap_content" android:layout_height="wrap_content" android:text="Permite controle do sistema" android:textColor="@color/muted" android:textSize="8.5sp" /></LinearLayout>
                    <View android:layout_width="7dp" android:layout_height="7dp" android:background="@drawable/status_dot" /><TextView android:id="@+id/accessibilityStatus" android:layout_width="wrap_content" android:layout_height="wrap_content" android:layout_marginLeft="5dp" android:text="verificando" android:textColor="@color/success" android:textSize="9sp" /><com.google.android.material.button.MaterialButton android:id="@+id/openAccessibility" style="@style/Widget.Material3.Button.TextButton" android:layout_width="31dp" android:layout_height="31dp" android:minWidth="0dp" android:insetLeft="0dp" android:insetRight="0dp" android:insetTop="0dp" android:insetBottom="0dp" app:icon="@drawable/ic_chevron_right" app:iconGravity="textStart" app:iconPadding="0dp" app:iconSize="16dp" app:iconTint="@color/muted" />
                </LinearLayout>
                <View android:layout_width="match_parent" android:layout_height="1dp" android:layout_marginLeft="41dp" android:background="#24282D" />
                <LinearLayout android:layout_width="match_parent" android:layout_height="46dp" android:gravity="center_vertical" android:orientation="horizontal">
                    <FrameLayout android:layout_width="32dp" android:layout_height="32dp" android:background="@drawable/diana_icon_circle"><ImageView android:layout_width="18dp" android:layout_height="18dp" android:layout_gravity="center" android:src="@drawable/ic_layers" app:tint="@color/textSecondary" /></FrameLayout>
                    <LinearLayout android:layout_width="0dp" android:layout_height="wrap_content" android:layout_marginLeft="9dp" android:layout_weight="1" android:orientation="vertical"><TextView android:layout_width="wrap_content" android:layout_height="wrap_content" android:text="Shizuku" android:textColor="@color/text" android:textSize="11.5sp" /><TextView android:layout_width="wrap_content" android:layout_height="wrap_content" android:text="Execução de comandos avançados" android:textColor="@color/muted" android:textSize="8.5sp" /></LinearLayout>
                    <View android:layout_width="7dp" android:layout_height="7dp" android:background="@drawable/status_dot" /><TextView android:id="@+id/shizukuStatus" android:layout_width="wrap_content" android:layout_height="wrap_content" android:layout_marginLeft="5dp" android:text="verificando" android:textColor="@color/success" android:textSize="9sp" /><com.google.android.material.button.MaterialButton android:id="@+id/allowShizuku" style="@style/Widget.Material3.Button.TextButton" android:layout_width="31dp" android:layout_height="31dp" android:minWidth="0dp" android:insetLeft="0dp" android:insetRight="0dp" android:insetTop="0dp" android:insetBottom="0dp" app:icon="@drawable/ic_chevron_right" app:iconGravity="textStart" app:iconPadding="0dp" app:iconSize="16dp" app:iconTint="@color/muted" />
                </LinearLayout>
                <View android:layout_width="match_parent" android:layout_height="1dp" android:layout_marginLeft="41dp" android:background="#24282D" />
                <LinearLayout android:layout_width="match_parent" android:layout_height="46dp" android:gravity="center_vertical" android:orientation="horizontal">
                    <FrameLayout android:layout_width="32dp" android:layout_height="32dp" android:background="@drawable/diana_icon_circle"><ImageView android:layout_width="18dp" android:layout_height="18dp" android:layout_gravity="center" android:src="@drawable/ic_monitor" app:tint="@color/textSecondary" /></FrameLayout>
                    <LinearLayout android:layout_width="0dp" android:layout_height="wrap_content" android:layout_marginLeft="9dp" android:layout_weight="1" android:orientation="vertical"><TextView android:layout_width="wrap_content" android:layout_height="wrap_content" android:text="Screen Vision" android:textColor="@color/text" android:textSize="11.5sp" /><TextView android:layout_width="wrap_content" android:layout_height="wrap_content" android:text="Acompanha sua tela em tempo real" android:textColor="@color/muted" android:textSize="8.5sp" /></LinearLayout>
                    <View android:layout_width="7dp" android:layout_height="7dp" android:background="@drawable/status_dot" /><TextView android:id="@+id/screenVisionRowStatus" android:layout_width="wrap_content" android:layout_height="wrap_content" android:layout_marginLeft="5dp" android:text="desligado" android:textColor="@color/muted" android:textSize="9sp" /><com.google.android.material.button.MaterialButton android:id="@+id/shareScreen" style="@style/Widget.Material3.Button.TextButton" android:layout_width="31dp" android:layout_height="31dp" android:minWidth="0dp" android:insetLeft="0dp" android:insetRight="0dp" android:insetTop="0dp" android:insetBottom="0dp" app:icon="@drawable/ic_chevron_right" app:iconGravity="textStart" app:iconPadding="0dp" app:iconSize="16dp" app:iconTint="@color/muted" />
                </LinearLayout>
            </LinearLayout>
        </LinearLayout>
'''
s=s[:start]+device+s[end:]
layout.write_text(s)
(res/'drawable/diana_device_group.xml').write_text('<shape xmlns:android="http://schemas.android.com/apk/res/android" android:shape="rectangle"><gradient android:angle="270" android:startColor="#C91B1E22" android:endColor="#C514171A"/><stroke android:width="1dp" android:color="#292D33"/><corners android:radius="18dp"/></shape>')
(res/'drawable/ic_heart.xml').write_text('<vector xmlns:android="http://schemas.android.com/apk/res/android" android:width="24dp" android:height="24dp" android:viewportWidth="24" android:viewportHeight="24"><path android:fillColor="@android:color/transparent" android:strokeColor="#FF989EA8" android:strokeWidth="1.5" android:strokeLineCap="round" android:strokeLineJoin="round" android:pathData="M12,21.35l-1.45,-1.32C5.4,15.36 2,12.28 2,8.5 2,5.42 4.42,3 7.5,3c1.74,0 3.41,0.81 4.5,2.09C13.09,3.81 14.76,3 16.5,3 19.58,3 22,5.42 22,8.5c0,3.78 -3.4,6.86 -8.55,11.54L12,21.35z"/></vector>')
(res/'drawable/diana_mark_exact.xml').write_text('''<vector xmlns:android="http://schemas.android.com/apk/res/android" android:width="64dp" android:height="64dp" android:viewportWidth="64" android:viewportHeight="64"><path android:fillColor="#FFFF575F" android:fillType="evenOdd" android:pathData="M28.5,14 L26.5,16 L19.5,28.5 L20,36 L22.5,39 L44,49.5 L48.5,50 L50.5,49 L52,46.5 L52,42.5 L38.5,18 L34,13.5 L31,13 Z M30,16.5 L31,16 L34,16.5 L36.5,20 L49.5,43.5 L49.5,45.5 L48,47 L45,47 L26.5,38 L22.5,35 L22,30 L25,24 Z"/><path android:fillColor="#FFFF575F" android:pathData="M18.5,30.5 L15,35.5 L11.5,42.5 L12,47.5 L14,49.5 L15.5,50 L20,49.5 L25,47.5 L24,46 L24.5,45.5 L17,47.5 L15.5,47 L14,45 L14,43.5 L17.5,37 Z"/></vector>''')
s=layout.read_text()
s=s.replace('app:iconTint="@color/textSecondary" />\n                    <TextView android:layout_width="wrap_content" android:layout_height="wrap_content" android:layout_marginTop="2dp" android:text="Histórico"','app:iconTint="@color/textSecondary" app:strokeWidth="1dp" app:strokeColor="@color/border" />\n                    <TextView android:layout_width="wrap_content" android:layout_height="wrap_content" android:layout_marginTop="2dp" android:text="Histórico"',1)
s=s.replace('app:iconTint="@color/textSecondary" />\n                    <TextView android:layout_width="wrap_content" android:layout_height="wrap_content" android:layout_marginTop="2dp" android:text="Configurações"','app:iconTint="@color/textSecondary" app:strokeWidth="1dp" app:strokeColor="@color/border" />\n                    <TextView android:layout_width="wrap_content" android:layout_height="wrap_content" android:layout_marginTop="2dp" android:text="Configurações"',1)
layout.write_text(s)
build=root/'app/build.gradle.kts'
s=build.read_text().replace('versionCode = 22','versionCode = 23').replace('versionName = "0.3.1"','versionName = "0.3.2"')
build.write_text(s)
print('Applied Diana v0.3.2 final visual pass')